import fs from 'node:fs'
import path from 'node:path'
import type { NitroConfig } from 'nitropack'

/**
 * Load prerender routes from JSON file generated by scripts/generate-prerender-routes.ts
 * This function is called during nitro:config hook
 */
export function loadPrerenderRoutes(nitroConfig: NitroConfig): void {
  const routesPath = path.join(process.cwd(), '.nuxt', 'prerender-routes.json')

  try {
    if (fs.existsSync(routesPath)) {
      const routes: string[] = JSON.parse(fs.readFileSync(routesPath, 'utf-8'))

      if (!nitroConfig.prerender) {
        nitroConfig.prerender = {}
      }
      if (!nitroConfig.prerender.routes) {
        nitroConfig.prerender.routes = []
      }
      nitroConfig.prerender.routes.push(...routes)
      console.log(`Loaded ${routes.length} prerender routes from ${routesPath}`)
    } else {
      console.warn(
        `Prerender routes file not found at ${routesPath}. Run 'npx tsx scripts/generate-prerender-routes.ts' first.`,
      )
    }
  } catch (error) {
    console.error('Failed to load prerender routes:', error)
  }
}
