export { UniversityRepository } from './UniversityRepository'
export { ReviewRepository } from './ReviewRepository'
export { FAQRepository } from './FAQRepository'
export { ApplicationRepository } from './ApplicationRepository'
export { BlogRepository } from './BlogRepository'