name: Migrate (manual)

on:
  workflow_dispatch:

concurrency:
  group: migrate-${{ github.ref }}
  cancel-in-progress: false

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - name: SSH auth
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: known_hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" >> ~/.ssh/known_hosts || true
          chmod 600 ~/.ssh/known_hosts || true

      - name: Run migration command remotely
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: root
          SSH_PORT: ${{ secrets.SSH_PORT }}
        run: |
          set -euo pipefail
          ssh -o StrictHostKeyChecking=no -p "${SSH_PORT:-22}" "${SSH_USER}@${SSH_HOST}" bash -s <<'EOF'
          set -euo pipefail
          cd /root/apps/edu.turkish
          docker compose exec app npx prisma migrate deploy
          EOF
